apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3000        # Port exposed by the service
      targetPort: 3000  # Port your app is listening on
  type: ClusterIP       # Default and ideal for internal communication
